/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User_Portal;

//import online_recruitment_system.User_Portal.*;

import Admin_Panel.Admin_Portal;
import java.awt.event.KeyEvent;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import online_recruitment_system.Hashing;
import online_recruitment_system.Home_page;


/**
 *
 * @author Nonit_Mittal
 */
public class Login_Page extends javax.swing.JFrame {

    /**
     * Creates new form Login_Page
     */
    public Login_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        emailid = new javax.swing.JTextField();
        passwrd = new javax.swing.JPasswordField();
        login = new javax.swing.JLabel();
        regist = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 255, 255));
        jButton1.setText("Log-In");
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 255, 255));
        jButton3.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 102));
        jButton3.setText("Register for Free");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jButton3.setContentAreaFilled(false);
        jButton3.setOpaque(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailid.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        emailid.setForeground(new java.awt.Color(153, 255, 255));
        emailid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailid.setBorder(null);
        emailid.setOpaque(false);
        emailid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailidActionPerformed(evt);
            }
        });
        emailid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailidKeyPressed(evt);
            }
        });
        getContentPane().add(emailid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 290, 280, 40));

        passwrd.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        passwrd.setForeground(new java.awt.Color(153, 255, 255));
        passwrd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwrd.setBorder(null);
        passwrd.setEchoChar('\u0080');
        passwrd.setOpaque(false);
        passwrd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwrdKeyPressed(evt);
            }
        });
        getContentPane().add(passwrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 385, 280, 40));

        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 510, 260, 60));

        regist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registMouseClicked(evt);
            }
        });
        getContentPane().add(regist, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 640, 270, 50));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_new/back_127px.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 110, 90));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/login_back.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String email = emailid.getText();
        String pass = passwrd.getText();
        
    if(email.isBlank()){
         JOptionPane.showMessageDialog(this,"E-Mail not Entered.");
    }if(pass.isBlank()){
        JOptionPane.showMessageDialog(this,"Password not Entered.");
    }
    else{
        try{
            Connection con = online_recruitment_system.Online_Recruitment_System.connect();
            String sql = "SELECT * FROM SHREY.USER_LOGIN,SHREY.LOGIN_INFO, SHREY.USER_INFO WHERE SHREY.USER_LOGIN.EMAIL_ID = '"+email+"' AND (SHREY.USER_LOGIN.EMAIL_ID=SHREY.USER_INFO.EMAIL_ID OR SHREY.USER_LOGIN.EMAIL_ID=SHREY.LOGIN_INFO.EMAIL_ID) ";

            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            
            pass=Hashing.hashPassword(pass);
            
            if(rs.next()){
                if(rs.getString("PASSWORD").equals(pass)){
                    
                    if(rs.getBoolean("ADMIN")==false){
                        JOptionPane.showMessageDialog(this,"Login Successful....");
                        dispose();
                        String name = rs.getString("FULL_NAME");
                        new USER_PORTAL(name,email).setVisible(true);}
                    else{
                        if(rs.getBoolean("ADMIN")==true){
                            JOptionPane.showMessageDialog(this,"Login Successful....");
                            dispose();
                            new Admin_Portal(email).setVisible(true);
                        }
                    
                    
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this,"Incorrect Password...");
                    passwrd.setText("");
                }
            }
            else{
                JOptionPane.showMessageDialog(this,"Login Un-Successful. \nUser Not Found..");
                emailid.setText("");
                passwrd.setText("");
            }
            stmt.close();
            con.close();
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog (null,ex.getMessage());  
        }   catch (NoSuchAlgorithmException ex) { 
                 System.out.println(ex.getMessage());
            } 
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        new Register_0().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void passwrdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwrdKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jButton1.doClick();
        }if(evt.getKeyCode() == KeyEvent.VK_UP){
            emailid.requestFocus();
        }     
    }//GEN-LAST:event_passwrdKeyPressed

    private void emailidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailidKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            passwrd.requestFocus();
        }if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            passwrd.requestFocus();
        } 
    }//GEN-LAST:event_emailidKeyPressed

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
       jButton1.doClick(0);
    }//GEN-LAST:event_loginMouseClicked

    private void registMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registMouseClicked
        jButton3.doClick();
    }//GEN-LAST:event_registMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        dispose();
        new Home_page().setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel background;
    private javax.swing.JTextField emailid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel login;
    private javax.swing.JPasswordField passwrd;
    private javax.swing.JLabel regist;
    // End of variables declaration//GEN-END:variables
}
