/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User_Portal;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.security.NoSuchAlgorithmException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import online_recruitment_system.Hashing;
/**
 *
 * @author asus
 */
public class Register_Experienced extends javax.swing.JFrame {
    String email,fname,pass;

    /**
     * Creates new form NewJFrame
     */
    public Register_Experienced() {
        initComponents();
        e_info.setVisible(false);
        p_info.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reg = new javax.swing.JPanel();
        ac_info = new javax.swing.JPanel();
        mail = new javax.swing.JTextField();
        a_label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        conmail = new javax.swing.JTextField();
        passwrd = new javax.swing.JPasswordField();
        conpassword = new javax.swing.JPasswordField();
        passver = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        emailver = new javax.swing.JLabel();
        passStrength = new javax.swing.JLabel();
        p_info = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        citycountry = new javax.swing.JTextField();
        mobile = new javax.swing.JTextField();
        dob = new com.toedter.calendar.JDateChooser();
        gender = new javax.swing.JComboBox<>();
        mobver = new javax.swing.JLabel();
        e_info = new javax.swing.JPanel();
        qualify = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        skills = new javax.swing.JTextArea();
        expYear = new javax.swing.JSpinner();
        expMonth = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();
        gradYear = new com.toedter.calendar.JYearChooser();
        industry = new javax.swing.JCheckBox();
        file_path = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        up_resume = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        p_label = new javax.swing.JLabel();
        e_label = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        reg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ac_info.setBackground(new java.awt.Color(255, 255, 255));
        ac_info.setOpaque(false);
        ac_info.setLayout(null);

        mail.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        mail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 153)));
        mail.setOpaque(false);
        mail.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                mailCaretUpdate(evt);
            }
        });
        ac_info.add(mail);
        mail.setBounds(60, 100, 210, 20);

        a_label.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        a_label.setText("ACCOUNT INFORMATION");
        ac_info.add(a_label);
        a_label.setBounds(60, 0, 202, 31);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(2, 51, 102));
        jLabel4.setText("E-MAIL ID");
        ac_info.add(jLabel4);
        jLabel4.setBounds(62, 77, 70, 18);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(2, 51, 102));
        jLabel5.setText("retype E-MIAL ID");
        ac_info.add(jLabel5);
        jLabel5.setBounds(60, 130, 120, 18);

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(2, 51, 102));
        jLabel6.setText("PASSWORD");
        ac_info.add(jLabel6);
        jLabel6.setBounds(60, 200, 90, 18);

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(2, 51, 102));
        jLabel7.setText("retype PASSWORD");
        ac_info.add(jLabel7);
        jLabel7.setBounds(60, 260, 130, 18);

        conmail.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        conmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 153)));
        conmail.setOpaque(false);
        conmail.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                conmailCaretUpdate(evt);
            }
        });
        ac_info.add(conmail);
        conmail.setBounds(60, 150, 210, 20);

        passwrd.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 153)));
        passwrd.setOpaque(false);
        passwrd.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                passwrdCaretUpdate(evt);
            }
        });
        ac_info.add(passwrd);
        passwrd.setBounds(60, 220, 210, 20);

        conpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 153)));
        conpassword.setOpaque(false);
        conpassword.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                conpasswordCaretUpdate(evt);
            }
        });
        conpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conpasswordActionPerformed(evt);
            }
        });
        ac_info.add(conpassword);
        conpassword.setBounds(60, 280, 210, 20);

        passver.setForeground(new java.awt.Color(153, 0, 51));
        passver.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ac_info.add(passver);
        passver.setBounds(60, 300, 210, 15);

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("NEXT");
        jButton1.setToolTipText("Enter Further Details...");
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ac_info.add(jButton1);
        jButton1.setBounds(120, 440, 70, 30);

        emailver.setForeground(new java.awt.Color(153, 0, 51));
        emailver.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ac_info.add(emailver);
        emailver.setBounds(60, 170, 210, 15);

        passStrength.setForeground(new java.awt.Color(153, 0, 51));
        passStrength.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ac_info.add(passStrength);
        passStrength.setBounds(60, 240, 210, 15);

        reg.add(ac_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 330, 470));

        p_info.setBackground(new java.awt.Color(255, 255, 255));
        p_info.setOpaque(false);

        name.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 153)));
        name.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(2, 51, 102));
        jLabel10.setText("FULL NAME");

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(7, 93, 149));
        jLabel11.setText("D.O.B");

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(2, 51, 102));
        jLabel12.setText("MOBILE NO.");

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(2, 51, 102));
        jLabel13.setText("GENDER");

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("NEXT");
        jButton2.setToolTipText("Enter Further Details...");
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(2, 51, 102));
        jLabel14.setText("CITY, COUNTRY");

        citycountry.setFont(new java.awt.Font("Bahnschrift", 1, 15)); // NOI18N
        citycountry.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 153)));
        citycountry.setOpaque(false);

        mobile.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        mobile.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 153)));
        mobile.setOpaque(false);
        mobile.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                mobileCaretUpdate(evt);
            }
        });

        dob.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 1, new java.awt.Color(153, 153, 153)));
        dob.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N

        gender.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        gender.setForeground(new java.awt.Color(0, 0, 102));
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        gender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gender.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        mobver.setForeground(new java.awt.Color(255, 0, 0));
        mobver.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout p_infoLayout = new javax.swing.GroupLayout(p_info);
        p_info.setLayout(p_infoLayout);
        p_infoLayout.setHorizontalGroup(
            p_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_infoLayout.createSequentialGroup()
                .addGroup(p_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_infoLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(p_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(p_infoLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(mobver, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p_infoLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(citycountry, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(p_infoLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        p_infoLayout.setVerticalGroup(
            p_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(2, 2, 2)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel11)
                .addGap(2, 2, 2)
                .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel12)
                .addGap(2, 2, 2)
                .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mobver, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(p_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel14)
                .addGap(2, 2, 2)
                .addComponent(citycountry, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        reg.add(p_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 320, 450));

        e_info.setBackground(new java.awt.Color(255, 255, 255));
        e_info.setOpaque(false);
        e_info.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        qualify.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        qualify.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 153)));
        qualify.setOpaque(false);
        e_info.add(qualify, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 131, 210, 20));

        jLabel17.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(2, 51, 102));
        jLabel17.setText("GRADUATION YEAR");
        e_info.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 11, 130, -1));

        jLabel18.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(2, 51, 102));
        jLabel18.setText("HIGHEST QUALIFICATION");
        e_info.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 111, 170, -1));

        jLabel19.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(2, 51, 102));
        jLabel19.setText("SKILLS");
        e_info.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 161, 90, -1));

        jLabel20.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(2, 51, 102));
        jLabel20.setText("Resume Path");
        e_info.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 90, -1));

        jLabel21.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(2, 51, 102));
        jLabel21.setText("Months");
        e_info.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 331, -1, -1));

        jLabel22.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(2, 51, 102));
        jLabel22.setText("Years");
        e_info.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 331, 30, 13));

        skills.setColumns(20);
        skills.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        skills.setLineWrap(true);
        skills.setRows(5);
        skills.setWrapStyleWord(true);
        skills.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 153)));
        skills.setOpaque(false);
        jScrollPane1.setViewportView(skills);

        e_info.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 181, 210, 99));

        expYear.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        expYear.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        expYear.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 1, new java.awt.Color(153, 153, 153)));
        e_info.add(expYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 311, 50, 20));

        expMonth.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        expMonth.setModel(new javax.swing.SpinnerNumberModel(0, 0, 12, 1));
        expMonth.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 1, new java.awt.Color(153, 153, 153)));
        e_info.add(expMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 311, 50, 20));

        jLabel24.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(2, 51, 102));
        jLabel24.setText("INDUSTRY WORKED");
        e_info.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 61, 130, -1));

        gradYear.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 1, new java.awt.Color(153, 153, 153)));
        e_info.add(gradYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 31, 210, 25));

        industry.setForeground(new java.awt.Color(255, 255, 255));
        industry.setText("      YES");
        industry.setOpaque(false);
        e_info.add(industry, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 81, -1, -1));

        file_path.setFont(new java.awt.Font("Bahnschrift", 0, 15)); // NOI18N
        file_path.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 153, 153)));
        file_path.setEnabled(false);
        file_path.setOpaque(false);
        e_info.add(file_path, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 378, 270, 20));

        jLabel23.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(2, 51, 102));
        jLabel23.setText("EXPERIENCE");
        e_info.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 291, 90, -1));

        up_resume.setBackground(new java.awt.Color(0, 0, 102));
        up_resume.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        up_resume.setForeground(new java.awt.Color(255, 255, 255));
        up_resume.setText("Upload Resume");
        up_resume.setToolTipText("Enter Further Details...");
        up_resume.setContentAreaFilled(false);
        up_resume.setOpaque(true);
        up_resume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_resumeActionPerformed(evt);
            }
        });
        e_info.add(up_resume, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 102));
        jButton3.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("REGISTER");
        jButton3.setToolTipText("Enter Further Details...");
        jButton3.setContentAreaFilled(false);
        jButton3.setOpaque(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        e_info.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 110, 30));

        reg.add(e_info, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 240, 330, 540));

        p_label.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        p_label.setText("PERSONAL INFORMATION");
        reg.add(p_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 220, 31));

        e_label.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        e_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e_label.setText("EDUCATIONAL INFORMATION");
        reg.add(e_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 200, 330, 31));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images_new/back_127px.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        reg.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 710, 110, 90));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/reg_exp_back_new.png"))); // NOI18N
        reg.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mailCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_mailCaretUpdate
        String email1 = mail.getText();
        String remail = conmail.getText();

        if(email1.length()>0){
            if (email1.equals(remail)) {
                emailver.setForeground(Color.green);
                emailver.setText("EMail-Id Match..");
            }
            else {
                emailver.setForeground(Color.red);
                emailver.setText("EMail-Id Not Match..");
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_mailCaretUpdate

    private void conmailCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_conmailCaretUpdate
        String email11 = mail.getText();
        String remail = conmail.getText();
        if(remail.length()>0){
            if (email11.equals(remail)) {
                emailver.setForeground(Color.green);
                emailver.setText("EMail-Id Match..");
            }
            else {
                emailver.setForeground(Color.red);
                emailver.setText("EMail-Id Not Match..");
            }
        }
    }//GEN-LAST:event_conmailCaretUpdate

    private void passwrdCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_passwrdCaretUpdate
        String pass = passwrd.getText();
        String confpass = conpassword.getText();
        if(pass.length()>0){
            if (pass.equals(confpass)) {
                passver.setForeground(Color.green);
                passver.setText("Password Match..");
            }
            else {
                passver.setForeground(Color.red);
                passver.setText("Password Not Match..");
            }
        }

        char [] alphaU = new char[]{'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'Z', 'Y', 'X', 'W', 'V', 'U', 'T', 'S', 'R', 'Q', 'P', 'O', 'N'};
        char [] alphaL = new char[]{'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'z', 'y', 'x', 'w', 'v', 'u', 't', 's', 'r', 'q', 'p', 'o', 'n'};
        char [] digit = new char[]{'1','2','3','4','5','6','7','8','9','0'};
        char [] special = new char[]{'!','@','#','$','%','^','&','*','(',')','-','+','=',' ','/','.',',','?','_'};
        int l = pass.length();

        boolean a = true;
        boolean b = true;
        boolean c = true;
        boolean d = true;
        int count = 0;
        if(l>=8){
            count ++;
        }
        for( int i = 0 ; i<l ; i++){
            for (int j = 0 ; j<26 ; j++){
                if ((pass.charAt(i) == alphaU[j]) && (a == true)){
                    count += 1;
                    a = false;
                }
                else if ((pass.charAt(i) == alphaL[j]) && (b == true)){
                    count += 1;
                    b = false;
                }
            }
            for (int k = 0 ; k<10 ; k++){
                if ((pass.charAt(i) == digit[k]) && (c == true)){
                    count += 1;
                    c = false;
                }
            }
            for (int m = 0 ; m<19 ; m++){
                if ((pass.charAt(i) == special[m]) && (d == true)){
                    count += 1;
                    d = false;
                }
            }
        }
        if (count == 3 || count == 4){
            passStrength.setForeground(Color.blue);
            passStrength.setText("Moderate Password");
        }else if (count == 5){
            passStrength.setForeground(Color.green);
            passStrength.setText("Strong Password");
        }else{
            passStrength.setForeground(Color.red);
            passStrength.setText("Weak Password");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_passwrdCaretUpdate

    private void conpasswordCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_conpasswordCaretUpdate
        String pass = passwrd.getText();
        String confpass = conpassword.getText();
        if(confpass.length()>0){
            if (pass.equals(confpass)) {
                passver.setForeground(Color.green);
                passver.setText("Password Match..");
            }
            else {
                passver.setForeground(Color.red);
                passver.setText("Password Not Match..");
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_conpasswordCaretUpdate

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        email = mail.getText();
        String cemail = conmail.getText();
        pass = passwrd.getText();
        String cpass = conpassword.getText();

        if (email.isEmpty() || cemail.isEmpty() || pass.isEmpty() || cpass.isEmpty()){
            JOptionPane.showMessageDialog(this,"Details are not complete..\nFields cannot be Empty..");
        }else if(pass.equals(cpass) && email.equals(cemail)){
            try{
                Connection con = online_recruitment_system.Online_Recruitment_System.connect();
                String sql1 = "select EMAIL_ID from SHREY.USER_LOGIN where EMAIL_ID = '"+email+"'";
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery(sql1);
                if(rs.next()){
                    JOptionPane.showMessageDialog(this,"E-Mail already taken..\n");
                }else{
                    stmt.close();
                    con.close();
                    rs.close();
                    p_info.setVisible(true);
                    
                }
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog (null,ex.getMessage());
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Password or EMAIL-ID do not Match..");
        }   
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            fname = name.getText();
            String mobno = mobile.getText();
            String city = citycountry.getText();

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(dob.getDate());

            if(!fname.isEmpty() && !mobno.isEmpty() && !city.isEmpty()){
                if(!mobver.getText().equals("Valid MobileNo..") ){
                    JOptionPane.showMessageDialog(this,"MobileNo, should be of 10 Digits..");

                }else{
                    e_info.setVisible(true);
                    
                }
            }else{
                JOptionPane.showMessageDialog(this,"Details are not complete..\nFields cannot be Empty..");
            }
            
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(this,"Details are not complete..\nFields cannot be Empty..");
        }
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void mobileCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_mobileCaretUpdate
        char [] num = new char []{'1','2','3','4','5','6','7','8','9','0'};
        String mobno = mobile.getText();
        int l = mobno.length();
        int count = 0;
        for (int i = 0 ; i<l ; i++){
            for (int j = 0 ; j<10 ; j++){
                if(mobno.charAt(i) == num[j]){
                    count += 1;
                    break;
                }
            }
        }
        if (l==10 && count == 10){
            mobver.setForeground(Color.green);
            mobver.setText("Valid MobileNo..");
        }
        else{
            mobver.setForeground(Color.red);
            mobver.setText("In-Valid MobileNo..");
        }
    }//GEN-LAST:event_mobileCaretUpdate

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            String stat = "Experienced";
            String email1 = mail.getText();
            String fname1 = name.getText();

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");// TODO add your handling code here:
            String date1 = sdf.format(dob.getDate());
            int year_dob = dob.getDate().getYear()+1900;

            String Mobileno1 = mobile.getText();
            String gender11 = gender.getSelectedItem().toString();
            String citycount1 = citycountry.getText();
            String gradYear1 = Integer.toString(gradYear.getYear());
            String highqualify1 = qualify.getText();
            String skill1 = skills.getText();
            String indust1 = "NO";
            if(industry.isSelected()){indust1="YES";}
            String expY = expYear.getValue().toString();
            String expM = expMonth.getValue().toString();
            String filep=file_path.getText();
            
            
            pass=Hashing.hashPassword(pass);

            if(!fname1.isEmpty() && !Mobileno1.isEmpty() && !citycount1.isEmpty() && !highqualify1.isEmpty() && !skill1.isEmpty() && !gradYear1.isEmpty() && !indust1.isEmpty() && !expY.isEmpty() && !expM.isEmpty()){
                if((gradYear.getYear() - year_dob) <=15 ){
                    JOptionPane.showMessageDialog(this,"Error : \n" + "  DOB = "+date1+", \n  Graduation Year = "+gradYear1 + " \nHow ?");
                }else if(!mobver.getText().equals("Valid MobileNo..")){
                    JOptionPane.showMessageDialog(this,"MobileNo, should be of 10 Digits..");
                }else{
                    int Y = Integer.parseInt(expY)*12;
                    int M = Integer.parseInt(expM);
                    int experience = Y+M;

                    PreparedStatement stmt;
                    int gradYear2 = Integer.parseInt(gradYear1);
                    try{
                        Connection con = online_recruitment_system.Online_Recruitment_System.connect();
                        String sql = "insert into SHREY.USER_INFO "
                        + "(STATUS,EMAIL_ID,FULL_NAME,D_O_B,MOBILE_NO,GENDER,CITY_COUNTRY,GRADUATION_YEAR,INDUSTRY_WORKER,HIGHER_QUALIFICATION,SKILLS,EXPERIENCE,RESUME) "
                        + "values(?,?,?,?,?,?,?,?,?,?,?,?,?)";
                        String sql1 = "insert into SHREY.USER_LOGIN(EMAIL_ID,PASSWORD) values('"+email+"','"+pass+"')";
                        Statement stmt1 = con.createStatement();
                        stmt = con.prepareStatement(sql);
                        stmt.setString(1, stat);
                        stmt.setString(2, email1);
                        stmt.setString(3,fname1);
                        stmt.setString(4, date1);
                        stmt.setString(5, Mobileno1);
                        stmt.setString(6,gender11);
                        stmt.setString(7, citycount1);
                        stmt.setInt(8, gradYear2);
                        stmt.setString(9, indust1);
                        stmt.setString(10, highqualify1);
                        stmt.setString(11, skill1);
                        stmt.setInt(12, experience);
                        stmt.setString(13,filep);

                        stmt.executeUpdate();
                        stmt1.executeUpdate(sql1);
                        JOptionPane.showMessageDialog(this,"You are REGISTERED Successfully..!");
                        stmt.close();
                        stmt1.close();
                        con.close();
                        dispose();
                        new USER_PORTAL(fname1,email).setVisible(true);
                    }
                    catch(SQLException ex){
                        JOptionPane.showMessageDialog (null,ex.getMessage());
                    }
                }
            }else{
                JOptionPane.showMessageDialog(this,"Details are not complete..\nFields cannot be Empty..");
            }
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(this,"Details are not complete..\nFields cannot be Empty..");
        } catch (NoSuchAlgorithmException ex) {
             System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        
        Date d = new Date();
        int pyear = d.getYear()+1900;
        gradYear.setEndYear(pyear);
        gradYear.setStartYear(pyear-30); 
        gradYear.setFont(new Font("Roboto Bk", Font.BOLD, 14));
        Date pre = new Date();
        String year = Integer.toString(pre.getYear()+1900-18);
        String month = Integer.toString(pre.getMonth()+1);
        String dat = Integer.toString(pre.getDate());
        String maxdate = year+"-"+month+"-"+dat;
        try {
            Date datemax = new SimpleDateFormat("yyyy-MM-dd").parse(maxdate);
            dob.setMaxSelectableDate(datemax);
        } catch (ParseException ex) {
            System.out.print(ex.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void conpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conpasswordActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        dispose();
        new Register_0().setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    private void up_resumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_resumeActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filepath = f.getAbsolutePath();
        file_path.setText(filepath);
    }//GEN-LAST:event_up_resumeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Experienced.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Experienced.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Experienced.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Experienced.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Experienced().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a_label;
    private javax.swing.JPanel ac_info;
    private javax.swing.JLabel back;
    private javax.swing.JLabel background;
    private javax.swing.JTextField citycountry;
    private javax.swing.JTextField conmail;
    private javax.swing.JPasswordField conpassword;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JPanel e_info;
    private javax.swing.JLabel e_label;
    private javax.swing.JLabel emailver;
    private javax.swing.JSpinner expMonth;
    private javax.swing.JSpinner expYear;
    private javax.swing.JTextField file_path;
    private javax.swing.JComboBox<String> gender;
    private com.toedter.calendar.JYearChooser gradYear;
    private javax.swing.JCheckBox industry;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField mobile;
    private javax.swing.JLabel mobver;
    private javax.swing.JTextField name;
    private javax.swing.JPanel p_info;
    private javax.swing.JLabel p_label;
    private javax.swing.JLabel passStrength;
    private javax.swing.JLabel passver;
    private javax.swing.JPasswordField passwrd;
    private javax.swing.JTextField qualify;
    private javax.swing.JPanel reg;
    private javax.swing.JTextArea skills;
    private javax.swing.JButton up_resume;
    // End of variables declaration//GEN-END:variables
}
